### ISSUE TITLE
Register Fails while typing Username

### ISSUE THREAD

**Issue by OperatingSystemCMD** [sova-software/cmdOS#8]
Hi there, there is a glitch that when I try to register it fails.

The System cannot find the path specified

cause Removed and/or Missing Files

**Comment by OperatingSystemCMD** [comment]
Hello there 

I'm working on a update called CMDOS 1.1
This update includes:
Saving Data
Worddos (Wordle DOS VERSION)
Bug Fixes

**Comment by bumbelbee777** [comment]
any progress?

**Comment by usarana** [comment]
Hi there!
I'm sorry that I didn't see your issue earlier. Unfortunately, cmdOS is not being updated and might eventually be cancelled. Anyways, good luck on your cmdOS fork!
